sentence = input("Enter a sentence: ")

print("Number of characters:", len(sentence))
print("Number of characters without spaces:", len(sentence.replace(" ", "")))
print("Number of words:", len(sentence.split()))
print("Number of vowels:", sum(1 for char in sentence if char.lower() in 'aeiou'))
print("Reversed sentence:", sentence[::-1])
print("Uppercase:", sentence.upper())
print("Lowercase:", sentence.lower())
print("Ends with punctuation:", sentence[-1] in '.,!?')
print("Starts withCapital:", sentence[0].isupper())
